### ISSUE TITLE
Copy editing/language pass

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-primaryelex-results#25]
Someone should put eyes on the text, titles, etc. before Tuesday

**Comment by cjdd3b** [comment]
I'll take a first pass today, then we can pass off to someone else.

**Comment by cjsinner** [comment]
Sending these to Casey tonight so he can make suggestions in the am

**Comment by cjsinner** [comment]
Casey has updated some copy in the spreadsheet and given the green light, so that just needs an update in the build

**Comment by cjdd3b** [comment]
Still waiting for Torey, so I'll do this now.
