### ISSUE TITLE
Tooltip polish

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-primaryelex-results#30]
Not high priority! Basically everything else is worth doing first:

 - [x] Default sort order (with no results) should be alphabetical or otherwise match the main results table for the mapped race.
  - [ ] Consider absolute positioning the tooltip to follow the cursor
  - [ ] Watch the z-index of the tooltip so it doesn't look weird when going over/under the fixed nav

**Comment by zzolo** [comment]
Re: z-index.  I think the answer is to have the z-index of the nav set and be higher than the tooltip.

**Comment by cjsinner** [comment]
I can increase the z-index of the nav set if it's not already done.
