### ISSUE TITLE
Better anchor linking

### ISSUE THREAD

**Issue by zzolo** [striblab/2018-primaryelex-results#34]
When you come to the page with an anchor, such as `#courts`, or if you click the nav, you are brought to that section.  But, the sticky navigation is on top of it and the heading is usually hidden.

The probably easier way to fix this is to add top padding to the element that is being linked to.  This will affect spacing, and requires a bit of CSS management.

**Comment by cjsinner** [comment]
Got most of this done/adjusted ....... a couple of the state offices are still fudgy since it seems like the top padding has to be like 3-4 em in order to be just right. Will work on more later.

**Comment by cjsinner** [comment]
This is fixed on desktop with some refactoring of the css, but is still a little fudgy on mobile.
