### ISSUE TITLE
For Monday's test: Make sure Appeals Court District 2 doesn't tabulate votes

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-primaryelex-results#35]
There are two candidates for the seat, but it seems they both just got check marks last time: https://ballotpedia.org/Minnesota_intermediate_appellate_court_elections,_2018

**Comment by zzolo** [comment]
Yeah, in a nonpartisan primary, its pick 2 times the number of actual seats, so in this case, 2 people will win the primary.

**Comment by cjdd3b** [comment]
There will be no votes.
