### ISSUE TITLE
Weird tooltip bug on www

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-primaryelex-results#38]
To replicate:

1. Go to the preview page on www.startribune.com

2. Hover over St. Louis County (Duluth)

3. Move your mouse left over the tooltip. The tooltip won't move out of the way and will start flashing rapidly.

**Comment by cjdd3b** [comment]
Should specify that this seems to only be a problem on our site, not in the dev environment.

**Comment by zzolo** [comment]
This should be fixed.
