### ISSUE TITLE
Mobile map key dots showing up on random state legislative race

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-primaryelex-results#40]
<img width="277" alt="screen shot 2018-08-12 at 11 53 35 am" src="https://user-images.githubusercontent.com/947791/44004323-794196b4-9e26-11e8-8fef-e72a2cbce16b.png">

**Comment by cjdd3b** [comment]
Maybe because the name is Johnson?

**Comment by zzolo** [comment]
Yeah, it's most certainly because of that.  Will have to change that class mechanism.

**Comment by zzolo** [comment]
Should be good.  Just used the candidate ID instead of last name.  And used the styles in the county map styling to make it a bit easier to manage.
