### ISSUE TITLE
Data not loading on IE11 Browserstack test

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-primaryelex-results#42]
Might be a fluke, but would be good to check on IE11 on an actual Windows machine.

**Comment by cjsinner** [comment]
I'm looking on my localhost on IE11 and it's not loading. So .... that's a curious thing.

**Comment by cjdd3b** [comment]
Any useful messages in the developer console?

**Comment by cjdd3b** [comment]
Looking a little more closely at this, the issue seems to be IE11's lack of
support for arrow functions:
https://stackoverflow.com/questions/40216015/arrow-function-not-working-in-ie-why

Not sure what best solution is, but perhaps we can use Babel to transpile
an ES5 version of the code that just opens in IE11?

**Comment by zzolo** [comment]
Well, in theory, babel should be transpiling to deal with IE11 (and arrow functions).  Will check it out.
https://github.com/striblab/2018-primaryelex-results/blob/master/browserslist

**Comment by cjdd3b** [comment]
Here's couple screenshots for details:

Console error:

<img width="1074" alt="screen shot 2018-08-13 at 10 55 32 am" src="https://user-images.githubusercontent.com/947791/44043463-87adca52-9ee8-11e8-9b5b-d597cec5d26d.png">

And clicking through points at this. Note the cursor by the arrow function, which is why I suspect that's the issue:

<img width="562" alt="screen shot 2018-08-13 at 11 02 44 am" src="https://user-images.githubusercontent.com/947791/44043473-8dc8e160-9ee8-11e8-96f6-e1997657a6e5.png">

**Comment by zzolo** [comment]
I think this is a little more complicated.  Babel should cover it, but the Svelte compilation comes after the babel part and Svelte does not support IE.  In theory, we should be able to do Babel after Svelte, but I am still looking into how to do this correctly.

**Comment by zzolo** [comment]
I think I got this, though I am not 100% sure how or why.  But, definitely requires looking at all browsers again.

**Comment by cjdd3b** [comment]
👏. 👏. 👏. Looking forward to hearing how you did this.

**Comment by cjdd3b** [comment]
Just checked out the code and confirmed. Heroic.
