### ISSUE TITLE
Check marks green on Edge?

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-primaryelex-results#43]
NBD, just weird:

<img width="1034" alt="screen shot 2018-08-12 at 12 14 06 pm" src="https://user-images.githubusercontent.com/947791/44004518-45526c04-9e29-11e8-9fbc-8387c753fd64.png">

**Comment by cjsinner** [comment]
I was just wondering that, @zzolo -- the color just needs to be defined, I'm guessing. I can do that.
