### ISSUE TITLE
Updated date showing date, even though it same day

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-primaryelex-results#44]
<img width="285" alt="screen shot 2018-08-13 at 1 05 20 pm" src="https://user-images.githubusercontent.com/947791/44049420-a54f219e-9ef9-11e8-987d-177c01eeb6c2.png">

**Comment by zzolo** [comment]
I think this is actually because some of the test dates that come in through the AP are not necessarily accurate.  Like, ones that are in there now are actually tomorrow dates.

Let's follow it a bit tomorrow and see.
