### ISSUE TITLE
Social icon spacing pretty tight on mobile. Intentional?

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-primaryelex-results#48]
The y in the the headline seems to be dipping down into the icons here. No worries if it's intentional.

<img width="217" alt="screen shot 2018-08-14 at 7 45 09 am" src="https://user-images.githubusercontent.com/947791/44092490-357d9e2a-9f96-11e8-9e38-8cb7088b2a60.png">

Maybe due to this? https://github.com/striblab/2018-primaryelex-results/commit/cf4b84e29058f5167d20682aa066e5961e4b702f

**Comment by cjsinner** [comment]
not intentional and should now be fixed
