### ISSUE TITLE
Dropdown nav now broken on Mobile Safari (and maybe other things)

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-primaryelex-results#49]
Not sure if this was also due to a change from last night. But to replicate

1. Open the page in mobile Safari
2. Use the dropdown nav to navigate to a race (I did Senate)
3. Try clicking on the dropdown nav again to navigate to another race

For me, the nav pops up from the bottom then immediately disappears, so I can't click on another race to navigate to.

**Comment by cjsinner** [comment]
This is finicky for me - it works most of the time, but usually bumps me up the page in some way. I can't find anything I did last night that would have caused this.

**Comment by cjsinner** [comment]
I wonder if fixing the social button thing will fix this?

**Comment by cjdd3b** [comment]
Let's all discuss this later today. 

For somewhat mystifying reasons, this seems to fix the issue. It needs to be targeted only at iOS devices, hence the `userAgent` conditional. Otherwise the nav doesn't open on Android.

```
var userAgent = window.navigator.userAgent;
if (userAgent.match(/iPad/i) || userAgent.match(/iPhone/i)) {
  document.querySelector("#drop-nav select").addEventListener("touchstart", function(event) {
    event.preventDefault();
  });
}
```

I'm not totally sure where that code should live in Svelte World, but I dropped it into the `create()` method in `_head.svelte.html` and it seems to apply properly (?)

We should test this until we're confident in it or else find a better solution. If neither of those things pan out, the next best option might be to `display:none` the fixed nav on iOS for now. I'd argue that it's better to have a convenience feature not exist than to have it appear broken for a large number of users.

cc @zzolo

**Comment by zzolo** [comment]
Yeah, the `oncreate` makes sense as far as where to put it.  In theory, you should use a `ref`, but whatever.
https://svelte.technology/guide#refs

As far as the solution, I guess it makes sense.  I wonder what the default is for touching a select.  Doesn't seem like it would actually need to be ios specific, but whatevs.
