### ISSUE TITLE
Widget updates to static caching a long time

### ISSUE THREAD

**Issue by jeffhargarten** [striblab/2018-primaryelex-results#61]
Updates to this file:

http://static.startribune.com/news/elections/widgetMobile.html

took nearly 30 minutes to manifest on election night. The change was visible using a cache busting parameter on the URL. So this would work:

http://static.startribune.com/news/elections/widgetMobile.html?sdgsdg

But it remained unchanged otherwise. I was able to get around it using a the cache busted URL in the PhantomJS script itself.

Not a critical problem in the longrun, the change I tried to make was small and immaterial, but if we had to have made a much larger change, this could have been far worse.

**Comment by cjdd3b** [comment]
Closing in favor of #76
