### ISSUE TITLE
Bylines

### ISSUE THREAD

**Issue by cjdd3b** [striblab/2018-primaryelex-results#8]
You guys should take a byline on this! You did all the work!

**Comment by cjsinner** [comment]
Any thoughts on where that should go? The top seems .... weird? I can add a sources line and a credits line at the bottom. Holler if you think of anything else that should go down there

**Comment by cjsinner** [comment]
![image](https://user-images.githubusercontent.com/1641732/43807688-418a770a-9a6f-11e8-8d71-9eecafa0dba4.png)
